### ISSUE TITLE
Golang Panic from "sudo ddev hostname" 

### ISSUE THREAD

**Issue by joelpittet** [drud/quicksprint#41]
```
$ ./start_clean.sh
docker service running, continuing.

####
# This simple script starts a Drupal 8 checked out from head
# running in ddev with a fresh database.
#
# Make sure you've uploaded any patches from last issue
# you worked on before continuing, as this blow away
# local changes.
#
# Press y to continue, or any other key to exit the script.
# !!You don't need to hit enter!!.
#
####
y# Continuing
####
Project is not currently running. Try 'ddev start'.
No existing project to remove
Network ddev_default created
Starting environment for sprint-20180408-2046...
ddev needs to add an entry to your hostfile.
It will require administrative privileges via the sudo command, so you may be required
to enter your password for sudo. ddev is about to issue the command:
    sudo /usr/local/bin/ddev hostname sprint-20180408-2046.ddev.local 127.0.0.1
Please enter your password if prompted.
Running Command  Command=sudo /usr/local/bin/ddev hostname sprint-20180408-2046.ddev.local 127.0.0.1
Password:
PANI[0148] CheckErr(): ERROR:exit status 1
panic: (*logrus.Entry) (0x16320a0,0xc4201c6b90)

goroutine 1 [running]:
github.com/drud/ddev/vendor/github.com/sirupsen/logrus.Entry.log(0xc42009a140, 0xc4202e4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/drud/ddev/vendor/github.com/sirupsen/logrus/entry.go:125 +0x568
github.com/drud/ddev/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc4201c6b40, 0xc42014d8f0, 0x2, 0x2)
	/go/src/github.com/drud/ddev/vendor/github.com/sirupsen/logrus/entry.go:170 +0xaa
github.com/drud/ddev/vendor/github.com/sirupsen/logrus.(*Logger).Panic(0xc42009a140, 0xc42014d8f0, 0x2, 0x2)
	/go/src/github.com/drud/ddev/vendor/github.com/sirupsen/logrus/logger.go:236 +0x6d
github.com/drud/ddev/vendor/github.com/sirupsen/logrus.Panic(0xc42014d8f0, 0x2, 0x2)
	/go/src/github.com/drud/ddev/vendor/github.com/sirupsen/logrus/exported.go:107 +0x4b
github.com/drud/ddev/pkg/util.CheckErr(0x16c0a40, 0xc4201b74e0)
	/go/src/github.com/drud/ddev/pkg/util/errcheck.go:15 +0x81
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).AddHostsEntries(0xc4200c54a0, 0x0, 0x0)
	/go/src/github.com/drud/ddev/pkg/ddevapp/ddevapp.go:937 +0x5a1
github.com/drud/ddev/pkg/ddevapp.(*DdevApp).Start(0xc4200c54a0, 0x165f150, 0x1e)
	/go/src/github.com/drud/ddev/pkg/ddevapp/ddevapp.go:610 +0xe3
github.com/drud/ddev/cmd/ddev/cmd.appStart()
	/go/src/github.com/drud/ddev/cmd/ddev/cmd/start.go:44 +0x15e
github.com/drud/ddev/cmd/ddev/cmd.glob..func22(0x19a7920, 0x19d1f18, 0x0, 0x0)
	/go/src/github.com/drud/ddev/cmd/ddev/cmd/start.go:31 +0x20
github.com/drud/ddev/vendor/github.com/spf13/cobra.(*Command).execute(0x19a7920, 0x19d1f18, 0x0, 0x0, 0x19a7920, 0x19d1f18)
	/go/src/github.com/drud/ddev/vendor/github.com/spf13/cobra/command.go:654 +0x2a2
github.com/drud/ddev/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19a7020, 0x1003f6c, 0xc42008c058, 0x0)
	/go/src/github.com/drud/ddev/vendor/github.com/spf13/cobra/command.go:729 +0x2d4
github.com/drud/ddev/vendor/github.com/spf13/cobra.(*Command).Execute(0x19a7020, 0x0, 0x14e5650)
	/go/src/github.com/drud/ddev/vendor/github.com/spf13/cobra/command.go:688 +0x2b
github.com/drud/ddev/cmd/ddev/cmd.Execute()
	/go/src/github.com/drud/ddev/cmd/ddev/cmd/root.go:105 +0x3b
main.main()
	/go/src/github.com/drud/ddev/cmd/ddev/main.go:6 +0x20

```

**Comment by rfay** [comment]
@joelpittet it looks to me like maybe you didn't succeed entering the sudo password? Do you remember what happened right there? Do you have full sudo privileges? I'm pretty sure this looks like a legitimate ddev bug that hasn't ever been reported before. My bet is that if you do it again it will work. But just try `sudo ls` first, and if that works, this will probably work the next time you do it.

**Comment by joelpittet** [comment]
> Sorry, user pittet is not allowed to execute '/usr/bin/command ls -G' as root on Joels-MacBook-Pro.local.

Thanks Randy!

That's new to me... (fresh computer with encrypted disk).  I should probably check why I can't sudo.

**Comment by rfay** [comment]
Your error report is very much appreciated, I wrote it up on the ddev issue queue, https://github.com/drud/ddev/issues/780 - I'm sure it will be an easy fix.

**Comment by rfay** [comment]
If you don't mind I'm going to close this one, but we'll fix it in https://github.com/drud/ddev/issues/780
